### ISSUE TITLE
decbin

### ISSUE THREAD

**Issue by kiwina** [watzenare/PushApi#28]
decbin interesting choice i wander why the overhead and not simply the int for checking the preferences ??
PS:nice package inspired me to use laravel instead to build a full blown service

**Comment by watzenare** [comment]
I am using a bitmask in order to know which preferences the user has chosen. I am using one bit per device and it is an easy way to know which preferences have set the target user.
For now, the PushApi only supports 2 kind of devices (emails and smartphones) so I am using only 2 bits and it would be easy to know with an integer which option the user have set but, the more devices the PushApi supports, the more complexity to know which devices the user wants to receive the Push.

Here I put some examples in order to understand it:
+ For now, with 2 devices it is like this:
  - 0 = 00 = none
  - 1 = 01 = email
  - 2 = 10 = smartphone (the PushApi knows which device it should send)
  - 3 = 11 = all devices

As you can see here, you can remember the 4 integers of the preferences and you can know what preferences have set the user, but what happen when there are more devices and there are lots of combinations:
+ With 4 devices:
  - 0 = 00 = none
  - 1 = 01 = email
  - 2 = 10 = smartphone (the PushApi knows which device it should send)
  - 3 = 11 = all devices
  - 3 = 11 = all devices
  - 3 = 11 = all devices

**Comment by watzenare** [comment]
I am using a [bitmask](https://en.wikipedia.org/wiki/Mask_(computing)) in order to know which preferences the user has chosen. If you set one device per bit, when you have to check the option set by the user, you will only need to compare that option with the device mask (watch the example below, I don't know if I am being clear).

For now, the PushApi only support 2 kind of target devices (emails and smartphones) so I am using only 2 bits. In this case, it would be easy to know with an integer which option the user have set. The problem is, the more devices the PushApi supports, the more complexity to know in which devices the user wants to receive the Push.

Here are some examples in order to understand it:

For now, with 2 devices it is like this:
00 = 0 = none
**01** = 1 = email
**10** = 2 = smartphone (the PushApi knows which device it should send)
11 = 3 = all devices

As you can see here, you can remember the 4 integers of the preferences and you can know what preferences have set the user. In this case, the masks used are **01** and **10**.

With 4 devices (a, b, c, d) there are 15 different options to be set and it would be harder to remember the integers, the easiest option you have is to set a list of constants in order to know the meaning of each number. Using a bitmap, you only have to remember the masks and the comparison with the option should be easier:
00000 = 0 = none
**0001** = 1 = a
**0010** = 2 = b
**0100** = 4 = c
**1000** = 8 = d
0101 = 5 = only c and a
...
1101 = 13 = only d, c and a
...
1111 = 15 = all devices


Thanks for your comment!
